- name: Install(Group) development
  yum: pkg='@development' state=latest

- name: Install package
  yum: pkg={{ item }} state=installed
  with_items:
    - openssl-devel
    - zlib-devel
    - readline-devel
    - git

- name: Download rbenv
  git: repo=git://github.com/sstephenson/rbenv.git dest=~/.rbenv

- name: rbenv echo
  action: shell echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc

- name: rbenv echo
  action: shell echo 'eval "$(rbenv init -)"' >> ~/.bashrc

- name: Download ruby-build
  git: repo=git://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build

- name: Install ruby-build
  action: shell /bin/bash ~/.rbenv/plugins/ruby-build/install.sh chdir=~/.rbenv/plugins/ruby-build

- name: Install Ruby
  action: shell rbenv install {{ ruby_ver }}

- name: rbenv global 
  action: shell rbenv global {{ ruby_ver }}
  notify: rehash

- name: gem install
  action: shell rbenv exec gem install bundler foreman --no-ri --no-rdoc
  notify: rehash

- name: Setting ISUCON
  action: shell bundle install --deployment --without development chdir=/usr/local/src/isucon2/webapp/ruby/
  notify: rehash
